// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"goships/internal/appserver/config"
	"goships/internal/appserver/data"
	"goships/internal/appserver/server"
	"goships/internal/appserver/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(configConfig *config.Config) error {
	db := data.NewMysql(configConfig)
	dataData := data.NewData(db)
	serviceService := service.NewService(dataData)
	httpServer := server.NewHttp(configConfig, serviceService)
	error2 := StartServer(httpServer, dataData)
	return error2
}
